# This file configures the infrastructure for deploying LazyWrite on Render.
# By committing this file to your Git repository, Render can automatically
# build and deploy your services when you push changes.

services:
  # Python Backend for AI Processing
  - type: web
    name: lazywrite-backend
    env: python
    # This specifies that the service should be built from the 'backend' subdirectory.
    rootDir: backend
    # Render's high-performance instance type, necessary for running AI models.
    # Note: This is a paid plan. Check Render's pricing for details.
    plan: 'pro' # or a higher performance plan if needed
    # Specifies the command to start the web server.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    # Health check endpoint to ensure the service is running correctly.
    healthCheckPath: /health
    # Configuration for the persistent disk.
    disks:
      - name: lazywrite-data
        mountPath: /var/data/lazywrite
        sizeGB: 10 # Adjust size as needed for model caches and generated images
    # Environment variables required by the application.
    # IMPORTANT: The Stripe Secret Key should be added as a secret in the
    # Render dashboard, not committed here in plain text.
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 # Pinning the Python version for consistency
      - key: RENDER_DATA_DIR
        value: /var/data/lazywrite # The same path as our disk mountPath 