// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvdrygsiojauizzwiotc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZHJ5Z3Npb2phdWl6endpb3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTc5MzEsImV4cCI6MjA2NTY5MzkzMX0.bP3O_CKEjRwxL0oOtxaGpWSYtHC-VeNG8YOiXskgkMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);